DEBUG = False
DEBUG_TOOLBAR = False

ROOT_DIR = ''
TEMPLATES_DIR = ''


INSTALLED_APPS = []
MIDDLEWARES = []

WEBPACK_ASSETS_URL = None
WEBPACK_MANIFEST_PATH = '/asdasdasdasdasdasd/asdasdasdasd/'

STATIC_URL = '/assets/'
STATIC_PATH = ''

LIMIT = 100
OFFSET = 0